name: RT-Extension-MergeUsers
version: 0.02
abstract: Merges two users into the same effective user
author: Alex Vandiver <alexmv@bestpractical.com>
license: GPL version 2
distribution_type: module
no_index:
  directory:
    - html
    - inc
generated_by: Module::Install version 0.36
