---
abstract: 'Merges two users into the same effective user'
author:
  - 'Alex Vandiver <alexmv@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  RT: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-MergeUsers
no_index:
  directory:
    - html
    - inc
    - t
requires:
  Hook::LexWrap: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.04
